[2024-07-16T05:43:44.962+0530] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: raw_load_credit_scores.create_table manual__2024-07-16T00:13:42.895190+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-07-16T05:43:57.565+0530] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: raw_load_credit_scores.create_table manual__2024-07-16T00:13:42.895190+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-07-16T05:45:52.416+0530] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: raw_load_credit_scores.create_table manual__2024-07-16T00:13:42.895190+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
