[2024-07-14T03:11:21.208+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T03:11:21.225+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: parent_dag.trigger_raw_load_atms manual__2024-07-13T21:40:18.368196+00:00 [queued]>
[2024-07-14T03:11:21.233+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: parent_dag.trigger_raw_load_atms manual__2024-07-13T21:40:18.368196+00:00 [queued]>
[2024-07-14T03:11:21.233+0530] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T03:11:21.245+0530] {taskinstance.py:2330} INFO - Executing <Task(TriggerDagRunOperator): trigger_raw_load_atms> on 2024-07-13 21:40:18.368196+00:00
[2024-07-14T03:11:21.248+0530] {standard_task_runner.py:63} INFO - Started process 30745 to run task
[2024-07-14T03:11:21.251+0530] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'parent_dag', 'trigger_raw_load_atms', 'manual__2024-07-13T21:40:18.368196+00:00', '--job-id', '1372', '--raw', '--subdir', 'DAGS_FOLDER/dag_parent.py', '--cfg-path', '/tmp/tmpj0pa9j_7']
[2024-07-14T03:11:21.253+0530] {standard_task_runner.py:91} INFO - Job 1372: Subtask trigger_raw_load_atms
[2024-07-14T03:11:21.288+0530] {task_command.py:426} INFO - Running <TaskInstance: parent_dag.trigger_raw_load_atms manual__2024-07-13T21:40:18.368196+00:00 [running]> on host kali
[2024-07-14T03:11:21.346+0530] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='parent_dag' AIRFLOW_CTX_TASK_ID='trigger_raw_load_atms' AIRFLOW_CTX_EXECUTION_DATE='2024-07-13T21:40:18.368196+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-13T21:40:18.368196+00:00'
[2024-07-14T03:11:21.347+0530] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T03:11:21.398+0530] {trigger_dagrun.py:222} INFO - Waiting for raw_load_atms on 2024-07-13 21:41:21.360779+00:00 to become allowed state ['success'] ...
[2024-07-14T03:12:21.419+0530] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T03:12:21.438+0530] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/operators/trigger_dagrun.py", line 233, in execute
    raise AirflowException(f"{self.trigger_dag_id} failed with failed states {state}")
airflow.exceptions.AirflowException: raw_load_atms failed with failed states failed
[2024-07-14T03:12:21.453+0530] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=parent_dag, task_id=trigger_raw_load_atms, run_id=manual__2024-07-13T21:40:18.368196+00:00, execution_date=20240713T214018, start_date=20240713T214121, end_date=20240713T214221
[2024-07-14T03:12:21.469+0530] {standard_task_runner.py:110} ERROR - Failed to execute job 1372 for task trigger_raw_load_atms (raw_load_atms failed with failed states failed; 30745)
[2024-07-14T03:12:21.485+0530] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-14T03:12:21.527+0530] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-14T03:12:21.528+0530] {local_task_job_runner.py:222} INFO - ::endgroup::
