[2024-07-12T02:00:03.589+0530] {processor.py:161} INFO - Started process (PID=49261) to work on //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:00:03.592+0530] {processor.py:830} INFO - Processing file //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py for tasks to queue
[2024-07-12T02:00:03.598+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:00:03.597+0530] {dagbag.py:545} INFO - Filling up the DagBag from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:00:03.640+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:00:03.637+0530] {dagbag.py:355} ERROR - Failed to import: //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
Traceback (most recent call last):
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py", line 63, in <module>
    dag >> trigger_tasks[0]  # Start the sequence with the first child DAG
    ~~~~^^~~~~~~~~~~~~~~~~~
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 270, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DAG' object has no attribute 'update_relative'
[2024-07-12T02:00:03.641+0530] {processor.py:842} WARNING - No viable dags retrieved from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:00:03.678+0530] {processor.py:183} INFO - Processing //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py took 0.105 seconds
[2024-07-12T02:00:34.896+0530] {processor.py:161} INFO - Started process (PID=49989) to work on //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:00:34.902+0530] {processor.py:830} INFO - Processing file //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py for tasks to queue
[2024-07-12T02:00:34.905+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:00:34.904+0530] {dagbag.py:545} INFO - Filling up the DagBag from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:00:34.920+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:00:34.919+0530] {dagbag.py:355} ERROR - Failed to import: //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
Traceback (most recent call last):
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py", line 63, in <module>
    dag >> trigger_tasks[0]  # Start the sequence with the first child DAG
    ~~~~^^~~~~~~~~~~~~~~~~~
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 270, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DAG' object has no attribute 'update_relative'
[2024-07-12T02:00:34.921+0530] {processor.py:842} WARNING - No viable dags retrieved from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:00:34.941+0530] {processor.py:183} INFO - Processing //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py took 0.058 seconds
[2024-07-12T02:01:05.699+0530] {processor.py:161} INFO - Started process (PID=50525) to work on //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:01:05.701+0530] {processor.py:830} INFO - Processing file //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py for tasks to queue
[2024-07-12T02:01:05.705+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:01:05.705+0530] {dagbag.py:545} INFO - Filling up the DagBag from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:01:05.725+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:01:05.724+0530] {dagbag.py:355} ERROR - Failed to import: //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
Traceback (most recent call last):
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py", line 63, in <module>
    dag >> trigger_tasks[0]  # Start the sequence with the first child DAG
    ~~~~^^~~~~~~~~~~~~~~~~~
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 270, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DAG' object has no attribute 'update_relative'
[2024-07-12T02:01:05.726+0530] {processor.py:842} WARNING - No viable dags retrieved from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:01:05.751+0530] {processor.py:183} INFO - Processing //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py took 0.064 seconds
[2024-07-12T02:01:06.746+0530] {processor.py:161} INFO - Started process (PID=50543) to work on //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:01:06.747+0530] {processor.py:830} INFO - Processing file //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py for tasks to queue
[2024-07-12T02:01:06.749+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:01:06.749+0530] {dagbag.py:545} INFO - Filling up the DagBag from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:01:06.761+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:01:06.759+0530] {dagbag.py:355} ERROR - Failed to import: //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
Traceback (most recent call last):
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py", line 62, in <module>
    dag >> trigger_tasks[0]  # Start the sequence with the first child DAG
    ~~~~^^~~~~~~~~~~~~~~~~~
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 270, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DAG' object has no attribute 'update_relative'
[2024-07-12T02:01:06.761+0530] {processor.py:842} WARNING - No viable dags retrieved from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:01:06.781+0530] {processor.py:183} INFO - Processing //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py took 0.042 seconds
[2024-07-12T02:01:36.923+0530] {processor.py:161} INFO - Started process (PID=51170) to work on //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:01:36.929+0530] {processor.py:830} INFO - Processing file //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py for tasks to queue
[2024-07-12T02:01:36.931+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:01:36.931+0530] {dagbag.py:545} INFO - Filling up the DagBag from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:01:36.946+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:01:36.944+0530] {dagbag.py:355} ERROR - Failed to import: //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
Traceback (most recent call last):
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py", line 62, in <module>
    dag >> trigger_tasks[0]  # Start the sequence with the first child DAG
    ~~~~^^~~~~~~~~~~~~~~~~~
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 270, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DAG' object has no attribute 'update_relative'
[2024-07-12T02:01:36.947+0530] {processor.py:842} WARNING - No viable dags retrieved from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:01:36.971+0530] {processor.py:183} INFO - Processing //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py took 0.055 seconds
[2024-07-12T02:02:07.357+0530] {processor.py:161} INFO - Started process (PID=51810) to work on //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:02:07.362+0530] {processor.py:830} INFO - Processing file //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py for tasks to queue
[2024-07-12T02:02:07.364+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:02:07.364+0530] {dagbag.py:545} INFO - Filling up the DagBag from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:02:07.375+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:02:07.374+0530] {dagbag.py:355} ERROR - Failed to import: //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
Traceback (most recent call last):
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py", line 62, in <module>
    dag >> trigger_tasks[0]  # Start the sequence with the first child DAG
    ~~~~^^~~~~~~~~~~~~~~~~~
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 270, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DAG' object has no attribute 'update_relative'
[2024-07-12T02:02:07.376+0530] {processor.py:842} WARNING - No viable dags retrieved from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:02:07.395+0530] {processor.py:183} INFO - Processing //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py took 0.045 seconds
[2024-07-12T02:02:38.137+0530] {processor.py:161} INFO - Started process (PID=52317) to work on //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:02:38.143+0530] {processor.py:830} INFO - Processing file //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py for tasks to queue
[2024-07-12T02:02:38.148+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:02:38.147+0530] {dagbag.py:545} INFO - Filling up the DagBag from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:02:38.171+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:02:38.169+0530] {dagbag.py:355} ERROR - Failed to import: //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
Traceback (most recent call last):
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py", line 62, in <module>
    dag >> trigger_tasks[0]  # Start the sequence with the first child DAG
    ~~~~^^~~~~~~~~~~~~~~~~~
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 270, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DAG' object has no attribute 'update_relative'
[2024-07-12T02:02:38.172+0530] {processor.py:842} WARNING - No viable dags retrieved from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:02:38.192+0530] {processor.py:183} INFO - Processing //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py took 0.062 seconds
[2024-07-12T02:03:09.055+0530] {processor.py:161} INFO - Started process (PID=52897) to work on //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:03:09.061+0530] {processor.py:830} INFO - Processing file //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py for tasks to queue
[2024-07-12T02:03:09.063+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:03:09.063+0530] {dagbag.py:545} INFO - Filling up the DagBag from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:03:09.075+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:03:09.074+0530] {dagbag.py:355} ERROR - Failed to import: //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
Traceback (most recent call last):
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py", line 62, in <module>
    dag >> trigger_tasks[0]  # Start the sequence with the first child DAG
    ~~~~^^~~~~~~~~~~~~~~~~~
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 270, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DAG' object has no attribute 'update_relative'
[2024-07-12T02:03:09.076+0530] {processor.py:842} WARNING - No viable dags retrieved from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:03:09.094+0530] {processor.py:183} INFO - Processing //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py took 0.050 seconds
[2024-07-12T02:03:39.841+0530] {processor.py:161} INFO - Started process (PID=53391) to work on //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:03:39.848+0530] {processor.py:830} INFO - Processing file //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py for tasks to queue
[2024-07-12T02:03:39.850+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:03:39.849+0530] {dagbag.py:545} INFO - Filling up the DagBag from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:03:39.863+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:03:39.861+0530] {dagbag.py:355} ERROR - Failed to import: //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
Traceback (most recent call last):
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py", line 62, in <module>
    dag >> trigger_tasks[0]  # Start the sequence with the first child DAG
    ~~~~^^~~~~~~~~~~~~~~~~~
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 270, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DAG' object has no attribute 'update_relative'
[2024-07-12T02:03:39.864+0530] {processor.py:842} WARNING - No viable dags retrieved from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:03:39.882+0530] {processor.py:183} INFO - Processing //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py took 0.051 seconds
[2024-07-12T02:03:55.068+0530] {processor.py:161} INFO - Started process (PID=53713) to work on //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:03:55.070+0530] {processor.py:830} INFO - Processing file //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py for tasks to queue
[2024-07-12T02:03:55.071+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:03:55.071+0530] {dagbag.py:545} INFO - Filling up the DagBag from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:03:55.083+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:03:55.082+0530] {dagbag.py:355} ERROR - Failed to import: //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
Traceback (most recent call last):
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py", line 62, in <module>
    dag >> trigger_tasks[0]  # Start the sequence with the first child DAG
    ~~~~^^~~~~~~~~~~~~~~~~~
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 270, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DAG' object has no attribute 'update_relative'
[2024-07-12T02:03:55.084+0530] {processor.py:842} WARNING - No viable dags retrieved from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:03:55.102+0530] {processor.py:183} INFO - Processing //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py took 0.041 seconds
[2024-07-12T02:04:25.911+0530] {processor.py:161} INFO - Started process (PID=54177) to work on //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:04:25.912+0530] {processor.py:830} INFO - Processing file //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py for tasks to queue
[2024-07-12T02:04:25.915+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:04:25.914+0530] {dagbag.py:545} INFO - Filling up the DagBag from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:04:25.929+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:04:25.927+0530] {dagbag.py:355} ERROR - Failed to import: //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
Traceback (most recent call last):
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py", line 62, in <module>
    dag >> trigger_tasks[0]  # Start the sequence with the first child DAG
    ~~~~^^~~~~~~~~~~~~~~~~~
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 270, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DAG' object has no attribute 'update_relative'
[2024-07-12T02:04:25.930+0530] {processor.py:842} WARNING - No viable dags retrieved from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:04:25.955+0530] {processor.py:183} INFO - Processing //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py took 0.054 seconds
[2024-07-12T02:04:56.084+0530] {processor.py:161} INFO - Started process (PID=54731) to work on //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:04:56.090+0530] {processor.py:830} INFO - Processing file //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py for tasks to queue
[2024-07-12T02:04:56.092+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:04:56.092+0530] {dagbag.py:545} INFO - Filling up the DagBag from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:04:56.106+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:04:56.104+0530] {dagbag.py:355} ERROR - Failed to import: //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
Traceback (most recent call last):
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py", line 62, in <module>
    dag >> trigger_tasks[0]  # Start the sequence with the first child DAG
    ~~~~^^~~~~~~~~~~~~~~~~~
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 270, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DAG' object has no attribute 'update_relative'
[2024-07-12T02:04:56.107+0530] {processor.py:842} WARNING - No viable dags retrieved from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:04:56.127+0530] {processor.py:183} INFO - Processing //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py took 0.050 seconds
[2024-07-12T02:05:26.254+0530] {processor.py:161} INFO - Started process (PID=55226) to work on //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:05:26.255+0530] {processor.py:830} INFO - Processing file //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py for tasks to queue
[2024-07-12T02:05:26.257+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:05:26.257+0530] {dagbag.py:545} INFO - Filling up the DagBag from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:05:26.269+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:05:26.267+0530] {dagbag.py:355} ERROR - Failed to import: //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
Traceback (most recent call last):
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py", line 62, in <module>
    dag >> trigger_tasks[0]  # Start the sequence with the first child DAG
    ~~~~^^~~~~~~~~~~~~~~~~~
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 270, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DAG' object has no attribute 'update_relative'
[2024-07-12T02:05:26.270+0530] {processor.py:842} WARNING - No viable dags retrieved from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:05:26.294+0530] {processor.py:183} INFO - Processing //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py took 0.047 seconds
[2024-07-12T02:05:51.721+0530] {processor.py:161} INFO - Started process (PID=55565) to work on //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:05:51.727+0530] {processor.py:830} INFO - Processing file //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py for tasks to queue
[2024-07-12T02:05:51.730+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:05:51.729+0530] {dagbag.py:545} INFO - Filling up the DagBag from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:05:51.745+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:05:51.744+0530] {dagbag.py:355} ERROR - Failed to import: //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
Traceback (most recent call last):
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py", line 62, in <module>
    dag >> trigger_tasks[0]  # Start the sequence with the first child DAG
    ~~~~^^~~~~~~~~~~~~~~~~~
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 270, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DAG' object has no attribute 'update_relative'
[2024-07-12T02:05:51.746+0530] {processor.py:842} WARNING - No viable dags retrieved from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:05:51.766+0530] {processor.py:183} INFO - Processing //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py took 0.059 seconds
[2024-07-12T02:06:22.004+0530] {processor.py:161} INFO - Started process (PID=56215) to work on //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:06:22.010+0530] {processor.py:830} INFO - Processing file //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py for tasks to queue
[2024-07-12T02:06:22.013+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:06:22.012+0530] {dagbag.py:545} INFO - Filling up the DagBag from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:06:22.024+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:06:22.022+0530] {dagbag.py:355} ERROR - Failed to import: //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
Traceback (most recent call last):
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py", line 62, in <module>
    dag >> trigger_tasks[0]  # Start the sequence with the first child DAG
    ~~~~^^~~~~~~~~~~~~~~~~~
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 270, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DAG' object has no attribute 'update_relative'
[2024-07-12T02:06:22.024+0530] {processor.py:842} WARNING - No viable dags retrieved from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:06:22.043+0530] {processor.py:183} INFO - Processing //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py took 0.059 seconds
[2024-07-12T02:06:26.835+0530] {processor.py:161} INFO - Started process (PID=56311) to work on //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:06:26.838+0530] {processor.py:830} INFO - Processing file //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py for tasks to queue
[2024-07-12T02:06:26.840+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:06:26.839+0530] {dagbag.py:545} INFO - Filling up the DagBag from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:06:26.852+0530] {processor.py:840} INFO - DAG(s) 'parent_dag' retrieved from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:06:27.012+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:06:27.012+0530] {override.py:1847} INFO - Created Permission View: can edit on DAG:parent_dag
[2024-07-12T02:06:27.036+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:06:27.035+0530] {override.py:1847} INFO - Created Permission View: can read on DAG:parent_dag
[2024-07-12T02:06:27.050+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:06:27.049+0530] {override.py:1847} INFO - Created Permission View: can delete on DAG:parent_dag
[2024-07-12T02:06:27.051+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:06:27.051+0530] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-12T02:06:27.065+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:06:27.065+0530] {dag.py:3118} INFO - Creating ORM DAG for parent_dag
[2024-07-12T02:06:27.068+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:06:27.067+0530] {dag.py:3954} INFO - Setting next_dagrun for parent_dag to None, run_after=None
[2024-07-12T02:06:27.110+0530] {processor.py:183} INFO - Processing //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py took 0.282 seconds
[2024-07-12T02:06:37.409+0530] {processor.py:161} INFO - Started process (PID=56595) to work on //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:06:37.410+0530] {processor.py:830} INFO - Processing file //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py for tasks to queue
[2024-07-12T02:06:37.411+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:06:37.411+0530] {dagbag.py:545} INFO - Filling up the DagBag from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:06:37.424+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:06:37.423+0530] {dagbag.py:355} ERROR - Failed to import: //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
Traceback (most recent call last):
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py", line 62, in <module>
    dag >> trigger_tasks[0]  # Start the sequence with the first child DAG
    ~~~~^^~~~~~~~~~~~~~~~~~
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 270, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DAG' object has no attribute 'update_relative'
[2024-07-12T02:06:37.425+0530] {processor.py:842} WARNING - No viable dags retrieved from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:06:37.443+0530] {processor.py:183} INFO - Processing //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py took 0.040 seconds
[2024-07-12T02:06:49.739+0530] {processor.py:161} INFO - Started process (PID=56784) to work on //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:06:49.740+0530] {processor.py:830} INFO - Processing file //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py for tasks to queue
[2024-07-12T02:06:49.742+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:06:49.741+0530] {dagbag.py:545} INFO - Filling up the DagBag from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:06:49.754+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:06:49.752+0530] {dagbag.py:355} ERROR - Failed to import: //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
Traceback (most recent call last):
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py", line 62, in <module>
    dag >> trigger_tasks[0]  # Start the sequence with the first child DAG
    ~~~~^^~~~~~~~~~~~~~~~~~
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 270, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DAG' object has no attribute 'update_relative'
[2024-07-12T02:06:49.755+0530] {processor.py:842} WARNING - No viable dags retrieved from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:06:49.773+0530] {processor.py:183} INFO - Processing //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py took 0.040 seconds
[2024-07-12T02:06:51.665+0530] {processor.py:161} INFO - Started process (PID=56822) to work on //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:06:51.666+0530] {processor.py:830} INFO - Processing file //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py for tasks to queue
[2024-07-12T02:06:51.668+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:06:51.668+0530] {dagbag.py:545} INFO - Filling up the DagBag from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:06:51.683+0530] {processor.py:840} INFO - DAG(s) 'parent_dag' retrieved from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:06:51.697+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:06:51.696+0530] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-12T02:06:51.721+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:06:51.721+0530] {dag.py:3954} INFO - Setting next_dagrun for parent_dag to None, run_after=None
[2024-07-12T02:06:51.769+0530] {processor.py:183} INFO - Processing //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py took 0.115 seconds
[2024-07-12T02:07:22.301+0530] {processor.py:161} INFO - Started process (PID=57527) to work on //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:07:22.307+0530] {processor.py:830} INFO - Processing file //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py for tasks to queue
[2024-07-12T02:07:22.311+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:07:22.310+0530] {dagbag.py:545} INFO - Filling up the DagBag from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:07:22.325+0530] {processor.py:840} INFO - DAG(s) 'parent_dag' retrieved from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:07:22.363+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:07:22.362+0530] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-12T02:07:22.380+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:07:22.380+0530] {dag.py:3954} INFO - Setting next_dagrun for parent_dag to None, run_after=None
[2024-07-12T02:07:22.414+0530] {processor.py:183} INFO - Processing //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py took 0.122 seconds
[2024-07-12T02:07:52.988+0530] {processor.py:161} INFO - Started process (PID=58136) to work on //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:07:52.995+0530] {processor.py:830} INFO - Processing file //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py for tasks to queue
[2024-07-12T02:07:52.997+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:07:52.997+0530] {dagbag.py:545} INFO - Filling up the DagBag from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:07:53.010+0530] {processor.py:840} INFO - DAG(s) 'parent_dag' retrieved from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:07:53.038+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:07:53.038+0530] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-12T02:07:53.050+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:07:53.050+0530] {dag.py:3954} INFO - Setting next_dagrun for parent_dag to None, run_after=None
[2024-07-12T02:07:53.071+0530] {processor.py:183} INFO - Processing //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py took 0.104 seconds
[2024-07-12T02:08:21.135+0530] {processor.py:161} INFO - Started process (PID=58564) to work on //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:08:21.136+0530] {processor.py:830} INFO - Processing file //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py for tasks to queue
[2024-07-12T02:08:21.138+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:08:21.138+0530] {dagbag.py:545} INFO - Filling up the DagBag from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:08:21.146+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:08:21.144+0530] {dagbag.py:355} ERROR - Failed to import: //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
Traceback (most recent call last):
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py", line 3, in <module>
    from airflow.operators.dagrun_operator import TriggerDagRunOperator, DagRunOrder
ImportError: cannot import name 'DagRunOrder' from 'airflow.operators.dagrun_operator' (unknown location)
[2024-07-12T02:08:21.147+0530] {processor.py:842} WARNING - No viable dags retrieved from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:08:21.173+0530] {processor.py:183} INFO - Processing //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py took 0.049 seconds
[2024-07-12T02:08:28.921+0530] {processor.py:161} INFO - Started process (PID=58706) to work on //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:08:28.923+0530] {processor.py:830} INFO - Processing file //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py for tasks to queue
[2024-07-12T02:08:28.928+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:08:28.928+0530] {dagbag.py:545} INFO - Filling up the DagBag from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:08:28.934+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:08:28.933+0530] {dagbag.py:355} ERROR - Failed to import: //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
Traceback (most recent call last):
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py", line 3, in <module>
    from airflow.operators.dagrun_operator import TriggerDagRunOperator, DagRunOrder
ImportError: cannot import name 'DagRunOrder' from 'airflow.operators.dagrun_operator' (unknown location)
[2024-07-12T02:08:28.935+0530] {processor.py:842} WARNING - No viable dags retrieved from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:08:28.964+0530] {processor.py:183} INFO - Processing //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py took 0.053 seconds
[2024-07-12T02:08:59.347+0530] {processor.py:161} INFO - Started process (PID=59358) to work on //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:08:59.350+0530] {processor.py:830} INFO - Processing file //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py for tasks to queue
[2024-07-12T02:08:59.353+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:08:59.352+0530] {dagbag.py:545} INFO - Filling up the DagBag from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:08:59.358+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:08:59.356+0530] {dagbag.py:355} ERROR - Failed to import: //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
Traceback (most recent call last):
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py", line 3, in <module>
    from airflow.operators.dagrun_operator import TriggerDagRunOperator, DagRunOrder
ImportError: cannot import name 'DagRunOrder' from 'airflow.operators.dagrun_operator' (unknown location)
[2024-07-12T02:08:59.359+0530] {processor.py:842} WARNING - No viable dags retrieved from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:08:59.393+0530] {processor.py:183} INFO - Processing //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py took 0.056 seconds
[2024-07-12T02:09:28.208+0530] {processor.py:161} INFO - Started process (PID=59974) to work on //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:09:28.209+0530] {processor.py:830} INFO - Processing file //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py for tasks to queue
[2024-07-12T02:09:28.210+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:09:28.209+0530] {dagbag.py:545} INFO - Filling up the DagBag from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:09:28.223+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:09:28.222+0530] {dagbag.py:355} ERROR - Failed to import: //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
Traceback (most recent call last):
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py", line 63, in <module>
    dag >> trigger_tasks[0]  # Start the sequence with the first child DAG
    ~~~~^^~~~~~~~~~~~~~~~~~
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 270, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DAG' object has no attribute 'update_relative'
[2024-07-12T02:09:28.224+0530] {processor.py:842} WARNING - No viable dags retrieved from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:09:28.241+0530] {processor.py:183} INFO - Processing //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py took 0.040 seconds
[2024-07-12T02:09:31.806+0530] {processor.py:161} INFO - Started process (PID=60058) to work on //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:09:31.807+0530] {processor.py:830} INFO - Processing file //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py for tasks to queue
[2024-07-12T02:09:31.810+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:09:31.808+0530] {dagbag.py:545} INFO - Filling up the DagBag from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:09:31.833+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:09:31.830+0530] {dagbag.py:355} ERROR - Failed to import: //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
Traceback (most recent call last):
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py", line 93, in <module>
    dag >> trigger_tasks[child_dags.index(child_dag_id)] >> task
    ~~~~^^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 270, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DAG' object has no attribute 'update_relative'
[2024-07-12T02:09:31.834+0530] {processor.py:842} WARNING - No viable dags retrieved from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:09:31.867+0530] {processor.py:183} INFO - Processing //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py took 0.070 seconds
[2024-07-12T02:09:59.439+0530] {processor.py:161} INFO - Started process (PID=60695) to work on //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:09:59.440+0530] {processor.py:830} INFO - Processing file //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py for tasks to queue
[2024-07-12T02:09:59.441+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:09:59.441+0530] {dagbag.py:545} INFO - Filling up the DagBag from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:09:59.466+0530] {processor.py:840} INFO - DAG(s) 'raw_load_customer_support', 'raw_load_investments', 'raw_load_savings_goals', 'raw_load_cards', 'raw_load_recurring_deposits', 'raw_load_employees', 'raw_load_cheques', 'raw_load_bill_payments', 'parent_dag', 'raw_load_branches', 'raw_load_online_banking', 'raw_load_accounts', 'raw_load_transactions', 'raw_load_fixed_deposits', 'raw_load_loans', 'raw_load_credit_scores', 'raw_load_service_charges', 'raw_load_atms', 'raw_load_insurance', 'raw_load_customers', 'raw_load_mortgage_applications' retrieved from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py
[2024-07-12T02:09:59.707+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:09:59.707+0530] {dag.py:3096} INFO - Sync 21 DAGs
[2024-07-12T02:09:59.724+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:09:59.724+0530] {dag.py:3954} INFO - Setting next_dagrun for parent_dag to None, run_after=None
[2024-07-12T02:09:59.729+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:09:59.729+0530] {dag.py:3954} INFO - Setting next_dagrun for raw_load_accounts to None, run_after=None
[2024-07-12T02:09:59.731+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:09:59.731+0530] {dag.py:3954} INFO - Setting next_dagrun for raw_load_atms to None, run_after=None
[2024-07-12T02:09:59.736+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:09:59.734+0530] {dag.py:3954} INFO - Setting next_dagrun for raw_load_bill_payments to None, run_after=None
[2024-07-12T02:09:59.739+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:09:59.739+0530] {dag.py:3954} INFO - Setting next_dagrun for raw_load_branches to None, run_after=None
[2024-07-12T02:09:59.741+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:09:59.741+0530] {dag.py:3954} INFO - Setting next_dagrun for raw_load_cards to None, run_after=None
[2024-07-12T02:09:59.743+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:09:59.743+0530] {dag.py:3954} INFO - Setting next_dagrun for raw_load_cheques to None, run_after=None
[2024-07-12T02:09:59.746+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:09:59.745+0530] {dag.py:3954} INFO - Setting next_dagrun for raw_load_credit_scores to None, run_after=None
[2024-07-12T02:09:59.748+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:09:59.747+0530] {dag.py:3954} INFO - Setting next_dagrun for raw_load_customer_support to None, run_after=None
[2024-07-12T02:09:59.749+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:09:59.749+0530] {dag.py:3954} INFO - Setting next_dagrun for raw_load_customers to None, run_after=None
[2024-07-12T02:09:59.753+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:09:59.753+0530] {dag.py:3954} INFO - Setting next_dagrun for raw_load_employees to None, run_after=None
[2024-07-12T02:09:59.758+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:09:59.758+0530] {dag.py:3954} INFO - Setting next_dagrun for raw_load_fixed_deposits to None, run_after=None
[2024-07-12T02:09:59.760+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:09:59.760+0530] {dag.py:3954} INFO - Setting next_dagrun for raw_load_insurance to None, run_after=None
[2024-07-12T02:09:59.762+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:09:59.762+0530] {dag.py:3954} INFO - Setting next_dagrun for raw_load_investments to None, run_after=None
[2024-07-12T02:09:59.764+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:09:59.763+0530] {dag.py:3954} INFO - Setting next_dagrun for raw_load_loans to None, run_after=None
[2024-07-12T02:09:59.766+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:09:59.766+0530] {dag.py:3954} INFO - Setting next_dagrun for raw_load_mortgage_applications to None, run_after=None
[2024-07-12T02:09:59.768+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:09:59.768+0530] {dag.py:3954} INFO - Setting next_dagrun for raw_load_online_banking to None, run_after=None
[2024-07-12T02:09:59.771+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:09:59.771+0530] {dag.py:3954} INFO - Setting next_dagrun for raw_load_recurring_deposits to None, run_after=None
[2024-07-12T02:09:59.773+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:09:59.773+0530] {dag.py:3954} INFO - Setting next_dagrun for raw_load_savings_goals to None, run_after=None
[2024-07-12T02:09:59.777+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:09:59.776+0530] {dag.py:3954} INFO - Setting next_dagrun for raw_load_service_charges to None, run_after=None
[2024-07-12T02:09:59.779+0530] {logging_mixin.py:188} INFO - [2024-07-12T02:09:59.779+0530] {dag.py:3954} INFO - Setting next_dagrun for raw_load_transactions to None, run_after=None
[2024-07-12T02:09:59.836+0530] {processor.py:183} INFO - Processing //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_parent.py took 0.406 seconds
